/**
 * @file deliveryConfig.ts
 * @description Auto-generated delivery destinations for noscut catalog
 * @generated by scripts/research-noscut-models.ts
 * @rule Do NOT edit manually — regenerate with the script
 */

export interface DeliveryCity {
  name: string;
  priceFrom: number;
  daysMin: number;
  daysMax: number;
}

export const DELIVERY_CITIES: DeliveryCity[] = [
  { name: "Москва", priceFrom: 15000, daysMin: 25, daysMax: 35 },
  { name: "Санкт-Петербург", priceFrom: 16000, daysMin: 27, daysMax: 37 },
  { name: "Новосибирск", priceFrom: 12000, daysMin: 20, daysMax: 30 },
  { name: "Владивосток", priceFrom: 8000, daysMin: 14, daysMax: 21 },
  { name: "Екатеринбург", priceFrom: 14000, daysMin: 23, daysMax: 33 },
  { name: "Минск", priceFrom: 20000, daysMin: 30, daysMax: 40 },
  { name: "Алматы", priceFrom: 18000, daysMin: 28, daysMax: 38 },
  { name: "Ташкент", priceFrom: 22000, daysMin: 32, daysMax: 42 },
];

export const DELIVERY_DISCLAIMER =
  "Сроки и стоимость доставки ориентировочные и зависят от загрузки транспорта. " +
  "Точные условия уточняйте у менеджера.";

export const DELIVERY_NOTE = "Отправим в любой город России и СНГ — уточните у менеджера.";
